<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AnalysisLevel>latest-all</AnalysisLevel>
		<AssemblyName>RentADeveloper.DbConnectionPlus.DatabaseAdapters.Sqlite</AssemblyName>
		<AssemblyTitle>rent-a-developer DbConnectionPlus SQLite Database Adapter</AssemblyTitle>
		<Authors>David Liebeherr</Authors>
		<Company>rent-a-developer</Company>
		<Copyright>Copyright © rent-a-developer / David Liebeherr</Copyright>
		<Description>SQLite database adapter for DbConnectionPlus.</Description>
		<DocumentationFile>RentADeveloper.DbConnectionPlus.DatabaseAdapters.Sqlite.xml</DocumentationFile>
		<EnableNETAnalyzers>True</EnableNETAnalyzers>
		<EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<ImplicitUsings>enable</ImplicitUsings>
		<IncludeSymbols>true</IncludeSymbols>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<PackageIcon>Resources\icon.png</PackageIcon>
		<PackageLicenseFile>LICENSE.md</PackageLicenseFile>
		<PackageProjectUrl>https://github.com/rent-a-developer/DbConnectionPlus</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageReleaseNotes>See CHANGELOG.md.</PackageReleaseNotes>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<RepositoryType>GIT</RepositoryType>
		<RepositoryUrl>https://github.com/rent-a-developer/DbConnectionPlus.git</RepositoryUrl>
		<RootNamespace>RentADeveloper.DbConnectionPlus.DatabaseAdapters.Sqlite</RootNamespace>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<TargetFramework>net8.0</TargetFramework>
		<TieredCompilation>true</TieredCompilation>
		<TieredPGO>true</TieredPGO>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<Version>2.0.0</Version>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\CHANGELOG.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\..\LICENSE.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Update="Resources\icon.png">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DbConnectionPlus\DbConnectionPlus.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.2" />
		<PackageReference Include="ErrorProne.NET.CoreAnalyzers" Version="0.1.2">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Roslynator.Analyzers" Version="4.15.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
