<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>RentADeveloper.DbConnectionPlus.DatabaseAdapters.Sqlite</AssemblyName>
    <AssemblyTitle>rent-a-developer DbConnectionPlus SQLite Database Adapter</AssemblyTitle>
    <Description>SQLite database adapter for DbConnectionPlus.</Description>
    <PackageId>DbConnectionPlus.DatabaseAdapters.Sqlite</PackageId>
    <RootNamespace>RentADeveloper.DbConnectionPlus.DatabaseAdapters.Sqlite</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DbConnectionPlus\DbConnectionPlus.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.11" />
  </ItemGroup>

</Project>
