<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>RentADeveloper.DbConnectionPlus.DatabaseAdapters.Oracle</AssemblyName>
    <AssemblyTitle>rent-a-developer DbConnectionPlus Oracle Database Adapter</AssemblyTitle>
    <Description>Oracle database adapter for DbConnectionPlus.</Description>
    <PackageId>DbConnectionPlus.DatabaseAdapters.Oracle</PackageId>
    <RootNamespace>RentADeveloper.DbConnectionPlus.DatabaseAdapters.Oracle</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DbConnectionPlus\DbConnectionPlus.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.26.300" />
  </ItemGroup>

</Project>
